language: node_js
node_js:
  - '8'

dist:     trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

cache:
  yarn: true
  directories:
    - node_modules

# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - yarn install
  # puppeteer's install script downloads Chrome

script:
  # too many errors, should be fixed or rules updated
  #- yarn lint
  # ensure the project builds correctly
  - yarn build
  - ls -al public/2017/flavors
  - ls -al public/2017/flavors/Results
  # starts static server
  - cd public && python -m SimpleHTTPServer &
  - sleep 6
  # ensure the capture works (because it relies on selectors)
  - cd cli && ./cli capture
