elastic:
  host:  localhost
  port:  9200
  log:   warning
  index: soj

type_form:
  base_url: https://api.typeform.com/v1/form

capture:
  baseUrl:   http://localhost:8000/2017
  outputDir: ../public/images/captures

  pages:
    - path:     /flavors/results/
      selector: .capture
    - path:     /flavors/developers/
      selector: .capture

    - path:     /front-end/results/
      selector: .capture
    - path:     /front-end/other/
      selector: .capture
    - path:     /flavors/developers/
      selector: .capture
    - path:     /front-end/worldwide/
      selector: .worldwide__grid

    - path:     /state-management/results/
      selector: .capture
    - path:     /state-management/other/
      selector: .capture
    - path:     /state-management/developers/
      selector: .capture
    - path:     /state-management/worldwide/
      selector: .worldwide__grid

    - path:     /back-end/results/
      selector: .capture
    - path:     /back-end/other/
      selector: .capture
    - path:     /back-end/developers/
      selector: .capture
    - path:     /back-end/worldwide/
      selector: .worldwide__grid

    - path:     /testing/results/
      selector: .capture
    - path:     /testing/other/
      selector: .capture
    - path:     /testing/developers/
      selector: .capture
    - path:     /testing/worldwide/
      selector: .worldwide__grid

    - path:     /css/results/
      selector: .capture
    - path:     /css/other/
      selector: .capture
    - path:     /css/developers/
      selector: .capture
    - path:     /css/worldwide/
      selector: .worldwide__grid

    - path:     /build-tools/results/
      selector: .capture
    - path:     /build-tools/other/
      selector: .capture
    - path:     /build-tools/developers/
      selector: .capture
    - path:     /build-tools/worldwide/
      selector: .worldwide__grid

report:
  frontend:
    keys:
      - React
      - Angular
      - Angular 2
      - Ember
      - Vue
      - Backbone
      - Polymer
      - Aurelia
      - No Front-End Framework
    freeform: Other Front-End Frameworks

  flavors:
    keys:
      - '"Plain" JavaScript (ES5)'
      - ES6
      - TypeScript
      - Flow
      - Elm
      - ClojureScript
      - Reason

  stateManagement:
    keys:
      - REST API
      - Redux
      - MobX
      - GraphQL
      - Relay/Relay Modern
      - Falcor
      - Apollo
      - Firebase
    freeform: Other Data Management Solutions

  styleManagement:
    keys:
      - Plain CSS
      - SASS/SCSS
      - Stylus
      - LESS
      - CSS-in-JS
      - Bootstrap
      - Foundation
    freeform: Other CSS solutions

  backend:
    keys:
      - Meteor
      - Express
      - Koa
      - Hapi
      - FeathersJS
      - Sails
      - Loopback
      - Keystone
    freeform: Other Back-End Tools

  testing:
    keys:
      - Mocha
      - Jasmine
      - Enzyme
      - Jest
      - Tape
      - Ava
    freeform: Other testing frameworks

  buildTools:
    keys:
      - Webpack
      - Grunt
      - Gulp
      - Browserify
      - NPM
      - Rollup
    freeform: Other build tools

  mobile:
    keys:
      - Native Apps
      - React Native
      - Ionic
      - PhoneGap/Cordova
      - NativeScript
      - Electron
    freeform: Other mobile/desktop apps solutions
