elastic:
  host:  localhost
  port:  9200
  log:   warning
  index: soj

typeform:
  token: EjgEahVHbf3ttJhHJuAFJVAnNAbUipmfquAUDCijz6Ly

currentSurvey: '2018'
dataOutputDir: ../surveys/2018/website/src/data/results
